title: GucciFlipFlop
author: James Bond
email: your-email@domain.com
theme: minima
description: Best blog ever, here you can hitta everything från gucci flipflop till James Bond

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
